dist: trusty
sudo: false

language: node_js
node_js: v8

cache:
  directories:
  - "$HOME/.npm"

env:
- DEBUG=tape-spawn

before_install:
- npm i -g npm@latest

install:
- npm ci
- npm run install:all

before_deploy:
- git-lfs pull
- make clean build-html

deploy:
  - provider: pages
    edge:
      branch: pages-ivar-set
    skip_cleanup: true
    github-token: "$GH_TOKEN"
    local-dir: dist
    on:
      branch: master
      tags: false
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: "hi@oncletom.io"
    api_key:
      secure: "GL2RVpkQ48gRmQxjXH1mD4w+pUiKkwO9NshqD2tStLMtHBcQwI5HxXsNzZw6kut2N7BGm0U5V67X4EJLMQqlp/MdOHHJyv5YwMmvZae1fKzHThA4j3PT7dx5Z35Jpv9QSrPKAv3qKiNhPDzWjiVCNeHKlsu2AIR1ECrK4RF/h7c="

env:
  global:
  - secure: "QEysjXiH91Nqb4PnIRwgroQBSE/HRLqVKU/fywtiPlmfPJJrCCyd+wckmsral83rckGJA+SxOCY2OYMt8ABZ+2yPWqf2S47clfO33bAqUaLmCRzEu12H/vTjPg9q7nmdX/jpexJ0KwbGp6zltIOo7pkd0We38RW9dh91LvDNrxw="
